### ISSUE TITLE
Cannot load model parameters from checkpoint

### ISSUE THREAD

**Issue by sami-haq99** [bert-nmt/ctx-bert-nmt#1]
I am training a doc_bert model with transformer_s2_iwslt_de_en arch. I have already trained baseline model, but getting following error when try to train bert for document level 1next context: 

Model will load checkpoint from /home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/examples/iwslt14_ende/tmp/fairseq_baseline/iwslt_de-en_H512/checkpoint_best.pt
Traceback (most recent call last):
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/fairseq/trainer.py", line 153, in load_checkpoint
self.get_model().load_state_dict(state['model'], strict=False if warmup_from_nmt else True)
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/fairseq/models/fairseq_model.py", line 72, in load_state_dict
return super().load_state_dict(state_dict, strict)
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1483, in load_state_dict
self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerS2Model:
size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([10152, 512]) from checkpoint, the shape in current model is torch.Size([117824, 512]).
size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([10152, 512]) from checkpoint, the shape in current model is torch.Size([117824, 512]).
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/train.py", line 311, in <module>
cli_main()
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/train.py", line 307, in cli_main
main(args)
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/train.py", line 71, in main
extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/fairseq/checkpoint_utils.py", line 127, in load_checkpoint
warmup_from_nmt=args.warmup_from_nmt,
File "/home/buraq/sami/nmt_toolkits/fair-bert-nmt/code/fairseq/trainer.py", line 156, in load_checkpoint
'Cannot load model parameters from checkpoint, '
Exception: Cannot load model parameters from checkpoint, please ensure that the architectures match.

Python: Python 3.7.10
CUDA: 10.1

Please help me resolve the issue.
Best Regards

**Comment by sami-haq99** [comment]
The issue has been resolved by using src and tgt dict same as baseline nmt model.
